### ISSUE TITLE
Update for Julia 1.0？

### ISSUE THREAD

**Issue by Gnimuc** [RoyiAvital/MatlabJuliaMatrixOperationsBenchmark#5]
bump

**Comment by RoyiAvital** [comment]
@Gnimuc ,
I intend to update to version 1.x.xxx once JuliaPro Distribution of Julia is updated to 1.x.xxx.
I was told it will take few weeks.

I also intend to check it as JuliaPro OpenlBLAS flavor vs. JuliaPro MKL flavor.

**Comment by Gnimuc** [comment]
closed since it seems that JuliaPro is not shipped with MKL for now.

**Comment by RoyiAvital** [comment]
@Gnimuc , You are right.
I wish they did.

If you are interested in it as me, make sure you post a wish like that in the forum.

**Comment by RoyiAvital** [comment]
@Gnimuc ,

I updated the benchmark.
It runs on Julia 1.2. It also compares Julia + OpenBLAS vs. Julia + `MKL.jl`.

**Comment by Gnimuc** [comment]
Nice work! Thanks!

**Comment by Gnimuc** [comment]
the huge gap in the matrix addition & reduction looks strange though. 🤔

**Comment by RoyiAvital** [comment]
Some  one said it might be me not using the fusion `.` dots correctly.
If you can have a look on the code in https://github.com/RoyiAvital/MatlabJuliaMatrixOperationsBenchmark/blob/master/JuliaMatrixBenchmark0001.jl and look at the functions (There 1-2 rows of text, so it will be swift) and tell me what should I improve I will run it again.

I think it is more related to the fact MATLAB automatically parallelize element wise operations on arrays while currently Julia doesn't do it.
